### ISSUE TITLE
[BUG] API key validation not generated

### ISSUE THREAD

**Issue by jeicken** [acrontum/openapi-nodegen-typescript-server#1]
**Describe the bug**
When using apiKey securityDefinition in the swagger, I would expect a apiKeyMiddleware validation to be generated for the routes protected. The JWT validation method is used instead.

**To Reproduce**
1. Create security validation like so:
securityDefinitions:
  apiKeyKnowledge:
    type: apiKey
    in: header
    name: x-api-key
2. Protect your routes in the swagger like so:
security:
  - apiKeyKnowledge: []
3. Generate the backend service with nodegen and expect the api key validation to be used

**Expected behavior**
Expect API key validation to be used

**Node & NPM version**
Node v10.16.3
NPM 6.12.0
openapi-nodege: 4.0.12

**Operating system:**
 - OS: [e.g. LinuxMint]
 - Version [e.g. 19.2]

**Additional context**

**Comment by jeicken** [comment]
@Acrontum-Carmichael  transferred

**Comment by Acrontum-Carmichael** [comment]
It actually looks correct, the middleware is provided the header name it should use.

Have you got the swagger path yml to look at?

**Comment by Acrontum-Carmichael** [comment]
The the middleware is an abstraction to:
https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/services/AccessTokenService.ts#L38

**Comment by jeicken** [comment]
yes but I don't want a JWT token validation, I want an APIkey validation. this should be possible as described here, if I am not wrong:
https://acrontum.github.io/openapi-nodegen/#/?id=route-security

get.yml which uses the securityDefinition:
`tags:
- salesforce
summary: Search salesforce entryies
description: Accepts an array of search parameters
operationId: apiV1SalesforceSearchPost
parameters:
  - $ref: ../../parameters/index.yml#/queryDocType
  - $ref: ../../parameters/index.yml#/queryLanguage
  - $ref: ../../parameters/index.yml#/querySearchTerm
  - $ref: ../../parameters/index.yml#/queryBrand
responses:
  200:
    description: success
    schema:
      type: array
      items:
        $ref: "../../definitions/index.yml#/SalesforceModel"
  404:
    description: 'Not found'
security:
  - apiKeyKnowledge: []
`

**Comment by Acrontum-Carmichael** [comment]
> `router.get( '/', accessTokenMiddleware(['x-api-key']), celebrate(searchValidators.apiV1SalesforceSearchPost), async (req: any, res: express.Response) => { return res.json( objectReduceByMap( await SearchDomain.apiV1SalesforceSearchPost(req.query), searchTransformOutputs.apiV1SalesforceSearchPost ) ); } );`
> 
> would expect:
> 
> `router.get( '/', apiKeyMiddleware(['x-api-key']), celebrate(searchValidators.apiV1SalesforceSearchPost), async (req: any, res: express.Response) => { return res.json( objectReduceByMap( await SearchDomain.apiV1SalesforceSearchPost(req.query), searchTransformOutputs.apiV1SalesforceSearchPost ) ); } );`

These two blocks of code are the same

**Comment by Acrontum-Carmichael** [comment]
I think i see what you mean, you have a route you wish to protect behind a simple api key, not jwt.

The middleware works by passing in a series of headers that should be checked. Out of the box the method will only handle jwt tokens. The authors of this set  of tpls have not had time to write in api key check yet.

**Comment by Acrontum-Carmichael** [comment]
So this issue is more an advancement to the existing code https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/services/AccessTokenService.ts#L38

I will close this now
