### ISSUE TITLE
Fix docker.compose.yml

### ISSUE THREAD

**Issue by jeicken** [acrontum/openapi-nodegen-typescript-server#16]
The docker compose yml is currently bootstrapped wrong:
* Network part is not correct
* Services should be named correctly
* Watcher image named wrongly - should be the same as the main image

**Comment by p-mcgowan** [comment]
I would highly recommend [tsc-watch](https://www.npmjs.com/package/tsc-watch) for this - I've been using it locally to save on running 2 images. Basically `tsc -w` but with a hook into transpile success, so you can build and, on success, run the server

**Comment by Acrontum-Carmichael** [comment]
Make sure to differentiate between tsc and ttsc.

This allows for the @/ import syntax to be transpiled correctly. Typescript doesn't offer this functionality out of the box.

**Comment by p-mcgowan** [comment]
The nice thing about that package is it lets you pass in the compiler - so in the exanple above, it's using `ttsc` instead of `tsc`

**Comment by jeicken** [comment]
ah cool yeah looks really nice! much cleaner than an own watcher service, never really liked that solution.... Would love to see a PR with this @p-mcgowan !

**Comment by jeicken** [comment]
The issue itself though was fixed with some simple changes for now...

**Comment by p-mcgowan** [comment]
Yeah it saves on precious ram - it might be worth looking into down the road, but it's only really useful for development since prod doesnt run the watcher
