### ISSUE TITLE
[BUG] Domain template jsdoc extra newline after description

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/openapi-nodegen-typescript-server#5]
**Describe the bug**
Newly generated domain files have an additional newline in the jsdocs, causing the linter to fail

**To Reproduce**

1. Add routes to api.yml
```
  /test:
    get:
      tags:
        - test
      summary: test
      operationId: testGet
      description: |
        Not a test
      responses:
        '200':
          description: Succeed
```
2. Generate with nodegen
3. linter should report errors for new domains
```
  /**
   * Operation ID: testGet
   * Summary: test
   * Description: not a test

   */
```
**Expected behavior**
No newline after description
```
  /**
   * Operation ID: testGet
   * Summary: test
   * Description: not a test
   */
```

**Node & NPM version**
Node 13.13.0 (also 12.16.2)
NPM 6.14.4
openapi-nodege: 5.1.8 (also 5.1.7)

**Operating system:**
OS: Ubuntu
Version: 18.04.4

**Additional context**
The error only occurs for multiline descriptions in the yml:
works:
```yml
description: not a test
```
fails:
```yml
description: |
  not a test
```

**Comment by Acrontum-Carmichael** [comment]
:) i had been quietly ignoring that one for a little while.. i think maybe this could fixed in the https://www.npmjs.com/package/generate-it core. The data is not manipulated in anyway and just passed straight into the templates.. could be trimmed there for additional white space and trailing or leading line breaks.

I will leave this one open for now and have a look a bit later. Also finishing off the AsyncAPI tpls for event driven architectures

**Comment by p-mcgowan** [comment]
Apparently it's not a bug, it's a feature (obvisouly).

Newlines are added to the end of multi-line strings by default:
```yaml
description: |
  There is a newline here ->
```

however, they can be trimmed:
```yaml
description: |-
  There is no newline here ->
```

If this is too much to ask, then there are 2 solutions referencing this issue:

[in the core](https://github.com/acrontum/generate-it/pull/21), this solution parses out and trims newlines from descriptions. This may be a bit heavy handed though, and potentially confusing.

[in the ts server repo](https://github.com/acrontum/openapi-nodegen-typescript-server/pull/7), the descriptions are trimmed in the templates. This may be more preferable as it is explicit and more fine-grained than the previous pull.

And of course, option 3 is to just change `description: |`  to `description: |-` in the specs.

**Comment by Acrontum-Carmichael** [comment]
Yup, the trim pipe from nunjucks was a nice idea so i merged it straight in. 

If the user writes a really long description this will result in a very long ling, but then prettier might be able to fix this automagically.

https://github.com/acrontum/generate-it/blob/master/src/lib/template/TemplateRenderer.ts#L51

https://github.com/acrontum/generate-it/blob/master/src/utils/prettyfyRenderedContent.ts
